### ISSUE TITLE
Using Cloud Firestore instead of EF & SQL for Identity.

### ISSUE THREAD

**Issue by sourav-paul** [GoogleCloudPlatform/dotnet-docs-samples#1023]
For user authentication and authorization I want to use ASP.NET Core Identity. All default setups are with entity framework using SQL.

I want to use Firestore as my project is using it already.

Is there any helper package just to replace EF and keeping the Identity implementation similar with Firestore? Something that replaces `AddEntityFrameworkStores<AppDbContext>()` for Firestore.

Or will I have to do it manually sending/getting data to Firestore on my own as we do for everything else?

```
services
    .AddIdentity<IdentityUser, IdentityRole>()
    .AddEntityFrameworkStores<AppDbContext>()  // <<= Any replacement for Firestore ?
    .AddDefaultTokenProviders();
```

**Comment by amanda-tarafa** [comment]
What you are looking for is a Firestore based [Custom storage provider for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1) and I'm pretty sure we don't maitain anything like that (@jskeet for final confirmation). But I believe you could write your own following the instructions in the link above.

**Comment by jskeet** [comment]
Indeed, I'm afraid we don't have that :(

**Comment by amanda-tarafa** [comment]
I'll be closing this issue now, since I believe we have answer your question. Feel free to leave a comment here if you believe otherwise.

Also, for Google APIs client libraries (including Google.Cloud.Firestore.V1) related issues, it is better if you post them at https://github.com/googleapis/google-cloud-dotnet.

Post in this repo we are in if you find issues with the samples themselves.
