### ISSUE TITLE
[Firestore]: Fix and reactivate flaky tests.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1162]
- FirestoreTests.GoogleCloudSamples.FirestoreTests.ListenMultipleTest
- FirestoreTests.GoogleCloudSamples.FirestoreTests.ListenDocumentTest

Build result [here](https://source.cloud.google.com/results/invocations/2d685bfb-f67c-48aa-9bb2-927b6f120d6f/targets/github%2Fdotnet-docs-samples%2Ffirestore%2Fapi%2FFirestoreTest%2FTestResults/tests;group=GoogleCloudSamples.FirestoreTests;test=GoogleCloudSamples.FirestoreTests.ListenDocumentTest;row=2)

**Comment by amanda-tarafa** [comment]
And FirestoreTests.GoogleCloudSamples.FirestoreTests.ListenForChangesTest

(Firestore tests could do with a rewrite)

**Comment by hemanshv** [comment]
Here is the pseudo code of [these samples](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/main/firestore/api/ListenData/Program.cs#L41):

1.  Add a callback listener to DocumentReference . That will be triggered when the given document is modified. The call back contains some print statements.
2.  Create/update the document.
3. Wait for 1 sec (Task.Delay(1000))
4. Stop the listener that is added in step 1.
5. Assert for print statements in callback.

[As per the failure logs](https://source.cloud.google.com/results/invocations/2d685bfb-f67c-48aa-9bb2-927b6f120d6f/log) here are my observations:

The callback attached to the listener has not been triggered because of which the assert statement failed.

The test for `ListenDocumentTest` and `ListenMutlipleTest` ran for 2 seconds and 362 milliseconds and 2 seconds and 937 milliseconds respectively.

From the above observations, we can see that both the tests ran for approximately 2.5 seconds but they have not triggered the listener callback. One reason for this could be because of insufficient delay (1 sec).

Although I ran the whole test suite 20 times (after unskipping these tests), I was not able to reproduce the issue. However, based on the above observations, my best guess is that the issue is caused by insufficient delay incase of unexpected network delay.

**Resolution**: Increase the delay in these tests from 1s to 3s and un-skipping these tests.

**Comment by amanda-tarafa** [comment]
Closing as possibly fixed by #2212 . We'll keep an eye on these tests and we'll reopen if this happens again.
Thanks @hemanshv !
