### ISSUE TITLE
[Spanner]: Instance Database limit (100) reached easily.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1189]
Alternatives:

- Keep decrementing the time to consider a DB stale.
  - Currently at 48hrs which already doesn't give us time to check on weekend failures.
  - If there's a lot of activity on the repo, and since all tests are executed on presubmit, we can always reach limit even if we delete tha databases inmediately after running the tests, we only need a set number of presubmit checks executing at the same time.
  - @laljikanjareeya You mentioned something about there being leftover DBs from before. I just tried deleting them on the UI but they have backups, I will try and submit a PR just for the sake of deleting them later, tweaking the fixture code to include this once DBs whose name is my-db-<not a timestamp>, and then close the PR. Maybe that fixes it and we don't have to consider anything else.
- Consider creating an instance per test run, and deleting the stale instances after 72hours.
  - It would address #1173 
  - What's the max amount of intances that we can have? We would created one per tests run, as opposed to many databases per test run?
  - How long does it take to create an instance?

@skuruppu and @laljikanjareeya thoughst welcomed.

**Comment by skuruppu** [comment]
@laljikanjareeya do you now why we might be creating so many databases? Is it that we're creating a database per test?

Either that, or the tests are run too many times a day since they're run for all PRs.

I think in Node.js, we create instances each run (it doesn't take very long, maybe a couple of seconds). Then instances are deleted at the end of the test. If the test crashes before the resources can be cleaned up, at the beginning of the test run, we delete all stale backups/instances that are older than 4 hours.

So we might have to do that here, especially given that the tests are run much more frequently in this repo than in the Node.js repo (which is spanner-specific).

Assigning to @laljikanjareeya to prepare a fix.

**Comment by amanda-tarafa** [comment]
Thanks for #1190 @laljikanjareeya, all the old DBs are now gone and we have less than 10 now.
Maybe let's keep things as are for a week and see if we see the resource exhasuted failures again. If we don't see them, it was just because of the old DBs. If wee see it, then we'll have to create new instances.
I'll leave this issue open so that I remember to check for failures in presubmits and CI by this time next week.

**Comment by laljikanjareeya** [comment]
We are creating only two database in test and one is for backup that we never delete.

CI Project there were more than 50 old databases and they never deleted based on current logic that we implemented, I have submitted a [PR](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1190) to delete old databases.

In Node.js we also use `SPANNERTEST_INSTANCE` environment variable for instance I don't know it been set on CI or not.

We can do same thing that @amanda-tarafa  mention create new instance on each test cycle and delete stale instances after 72 hours but it might be create problem of timeout in backup test.

I just created [PR#1191](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1191) to check if databases are more than 94 than delete 5 database from the list that has been created first.

**Comment by amanda-tarafa** [comment]
This should have been addressed by #1190 and #1191. Thanks @laljikanjareeya .
