### ISSUE TITLE
Transcript is returned repeated when there is a pause in the Microphone

### ISSUE THREAD

**Issue by jaimestuardo** [GoogleCloudPlatform/dotnet-docs-samples#1210]
Hello,

I am using your InfiniteStreaming class and it works, but, I realized that alternatives return the same text until a pause in the microphone is detected.

For example, these alteratives were printed in console window:

`hi Bill you name Susan canes the power` (4 times)
`hi Bill you name Susan canes the power of introverts` (4 times)
`hi Bill you name Susan canes the power of introverts as` (twice)
`hi Bill you name Susan canes the power of introverts as one` (twice)

And so on, until the full sentence was received:

`hi Bill you named Susan canes the power of introverts as one of your favorite TED Talks my question for you is how have you managed to succeed in a predominantly predominantly extra well and how can the education system with its increasing with extra bed and I do`

After that, the new sentence started.

How to avoid that behaviour? 

Thanks

Jaime

**Comment by jskeet** [comment]
I'll look into this on Monday.

**Comment by jskeet** [comment]
I'm not seeing this behavior with the sample as it's written. Interim results are provided by the API (because we specifically set `InterimResults=true` in the request) but the code doesn't print those - there's specifically a bit that has:

```csharp
// Uncomment this to see the details of interim results.
// Console.WriteLine($"Response: {response}");
```

Yes, if you look at the `Alternatives` property, you'll see those interim results - but if you don't want to take any notice of them, just ignore them.

You won't get a *stable* result until there's a pause because (I believe) the Speech API will take context into account - so later words can affect which result is chosen.

It's not clear to me what you're trying to achieve vs what's already provided. If you want to get stable results after a period but without any pausing, I think you'll need to ask the Speech API team via one of their [support routes](https://cloud.google.com/speech-to-text/docs/getting-support). That's not something we could do at a client library level - although of course you *could* decide to arbitrarily cut off a sentence after a certain time and "inject" a fake pause. I suspect that will negatively impact accuracy though.

**Comment by jskeet** [comment]
Closing given the lack of feedback.
