### ISSUE TITLE
[Cloud-SQL]: DB initilization should happen only once at application startup and not at connection acquisition.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1220]
On the thre cloud-sql samples, the DB is being initializes (attempted to) whenever a connection is requested. Before #1218 the connection was a singleton so this wasn't the biggest deal, but now a new connection is created  per request, so the DB should be initialized separate from the connection.

@jsimonweb assigning to you since we chatted about this but feel free to assign to someone else. Thanks!

**Comment by kurtisvg** [comment]
Hijacking this issue slightly, as I don't think that the changes in PR #1218 are showcasing the correct way to do connection pooling. While these changes now work with multiple requests, they also end up checking out a connection for the entire length of the request. We want to avoid this - instead we only want to borrow a connection from the pool while being used, and return it immediately after. 

[ADO.NET connection pooling](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling) documentation showcases the correct way to do this, which is:
1. ADO.NET automatically pools connections as long as the DB URI matches between them
2. Using the following pattern to checkout and return connections:
```csharp
using (SqlConnection connection = new SqlConnection( "YOUR-DB_URI"))
    {  
        connection.Open();
    }  
```

This means that rather than a pool object like most languages use, we need to have a global value that is constructed on start up from the environment vars, and use that to "create" (aka checkout) connections while each query is being performed.

**Comment by amanda-tarafa** [comment]
@kurtisvg The `using` pattern is just syntax sugar to guarantee that the object is disposed of at the end of the `using` block. When using dependency injection as we are doing in these examples (`services.AddScoped...`) the dependency injection mechanism [guarantees](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#disposal-of-services) that the object is disposed of at the end of its lifetime, and requires the object not to be disposed off explicitly by user code.

The lifetime of these connections is per request, because we are registering as scoped, and that's really not a problem because we only have [two possible requests](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/16da88f5ac12859f01a81b4d5ba5ad1cc955e846/cloud-sql/sql-server/Controllers/HomeController.cs#L28) and they both need the live connection almost from beginning to end, i.e. the connection is actually being used during the whole request. Just to clarify, you don't only need to open the connection inside the using block, you need to execute all commands that use the connection inside the using block. If a command that uses the connection is ran outside the using block you will get an `ObjectDisposedException`.

So, I really think there's no problem here because:

- ADO.NET pools connections automatically as per connection string. This app will have a connection pool.
- We requiere a connection per request that is injected on our controller constructor, this happens roughly at the beginning of the request.
- The connection is used throughout the request. There are really a couple of validations only, and that's really not significant in terms of holding on to the connection.
- The connection will be automatically disposed of by the dependency injection mechanism roughly at the end of the request, which returns it to the pool.

Also, I must say, this is not an uncommon pattern for ASP.NET + ADO.NET, and I'd rather we avoid trying to cover with a simple sample, complex or less common scenarios that are not particular of Google technologies but of Microsoft technologies. In my view, these samples should say "You can use SQL, MySql and Postgres in Google Cloud the same way you use them everywhere else" and I think this is already shown with these samples.

Is there anything I'm missing or something else that worries you?

**Comment by kurtisvg** [comment]
> The lifetime of these connections is per request, because we are registering as scoped, and that's really not a problem because we only have two possible requests and they both need the live connection almost from beginning to end, i.e. the connection is actually being used during the whole request.

While I think we could probably bikeshed over the performance impacts of correct scoping for the connection objects for _this_ specific app, the point of the sample is to provide an example for users to be able to learn from. If a user is using this as the basis for their application and employ a similar pattern in their app, they may have requests that don't need a connection or non-trivial calculations that should be performed outside the scope of connection object. If a user is using these samples to learn, the drawbacks of the current pattern are non-obvious, especially to less experienced developers.

Additionally, the `services.AddScoped` is harder to show in the snippet itself, where as the `using` statement will show up when it's linked from our [Managing Database Connections](https://cloud.google.com/sql/docs/mysql/manage-connections#open-close-csharp) page. 

> I'd rather we avoid trying to cover with a simple sample, complex or less common scenarios that are not particular of Google technologies but of Microsoft technologies. In my view, these samples should say "You can use SQL, MySql and Postgres in Google Cloud the same way you use them everywhere else" 

Typically I'd agree with you, but these samples are specifically designed to highlight best practices for a common framework in each language because:

1. Cloud SQL imposes connection limits, which if changed voids a user's SLA
2. Many of our runtime environments (App Engine, Run, GKE, etc) offer some kind of scaling for a user's application

So while technically this specific sample is using a third party framework, it's using it in the context of showcasing how to glue multiple GCP services together correctly.

**Comment by amanda-tarafa** [comment]
> If a user is using this as the basis for their application and employ a similar pattern in their app, they may have requests that don't need a connection or non-trivial calculations that should be performed outside the scope of connection object. If a user is using these samples to learn, the drawbacks of the current pattern are non-obvious, especially to less experienced developers.

I would argue very strongly against using a sample as the basis for an application and a Google sample for learning .NET (but that's another discussion ;) ). But if that were the case, if the sample is using the using pattern for the connections, then users that would benefit from the dependency injenction pattern would be missing out. Which goes directly to my point:

1. Both patterns are standard patterns in ASP.NET + ADO.NET.
2. They both have pros and cons which are all independent from Google technologies. There's not one thing that would make one work better with Google than the other, it all depends on the application itself. (DI won't create a connection for each request, it will create a connection for each request that asks for a connection, and yes, in this sample we are asking for a connection in each request, because we need one).
3. They both make correct use of the connection pool (which is what I understood you were worried about in your first comment).
4. They both work with this sample. They can both be considered "best practices" in the context of this sample and in the context of this sample running on Google.
5. We already have code for one of them :), and personally I don't see any tehcnical or didactical advantages in switching to the other. The only thing that might tip me to swithching is that, in our docs, it's easier to show the snippet with the using, than to show the DI bits and the snippet using the connection separately.

That said, I'm totally fine with either, and it's up to soda to decide what you want to show in samples. As long as is C# idiomatic, best practices, etc. I'm fine with it.

**Comment by kurtisvg** [comment]
> I would argue very strongly against using a sample as the basis for an application and a Google sample for learning .NET (but that's another discussion ;) ).

We'll have to agree to disagree here - I think taking sample applications and learning from them is a totally valid and very common use case, especially for full sample applications. Personally, it fits my style of learning to have a complete example to take and slowly change until it does what I want. Specifically for this sample, the only goal isn't just to show folks "how to connect" but it's "how to handle a connection pool in a particular web-framework". We used to just have "how to connect" samples and users found them unhelpful because they didn't properly apply to their use-cases (most commonly, web applications). 

> 1. Both patterns are standard patterns in ASP.NET + ADO.NET.
> 2. They both have pros and cons which are all independent from Google technologies. There's not one thing that would make one work better with Google than the other, it all depends on the application itself. (DI won't create a connection for each request, it will create a connection for each request that asks for a connection, and yes, in this sample we are asking for a connection in each request, because we need one).
> 3. They both make correct use of the connection pool (which is what I understood you were worried about in your first comment).
> 4. They both work with this sample. They can both be considered "best practices" in the context of this sample and in the context of this sample running on Google.
> 5. We already have code for one of them :), and personally I don't see any technical or didactical advantages in switching to the other. The only thing that might tip me to switching is that, in our docs, it's easier to show the snippet with the using, than to show the DI bits and the snippet using the connection separately.

The pattern of scoping a database connection to each request a connection receives is an anti-pattern. This pattern has only downsides compared to properly minimizing the scope of a connections lifetime, even if in those downsides are minimized in _this_ specific use of the application. If it is a standard pattern in ASP.NET + ADO.NET world, then this is a specific place where we should be pushing back in the ecosystem and saying "no, that's wrong - and here's why". 

If a connection is scoped to each request that means:
1. There an artificial limit on the number of requests that can be processed concurrently equal to the max side of the connection pool 
2. Requests that don't use a database connection still consume a limited resource until a request is completed (which, as mentioned is maybe not a major barrier to this application - depending on when ADO.NET returns the inits/destroys the connection ) 
3. Any time spent before or after the connection is blocking a resource that other requests are potentially blocked on (also _mostly_ not applicable - but easily could be in a non-obvious way) 

Additionally, there are a couple of bad practices that our implementation is currently doing specifically:
1. It attempts to run a "set up query" at the start of each request (which I believe was the original concern of this issue) 
2. Each connection created re-creates the connection string, rather than reusing a static one - which is potentially pretty expensive, given that multiple environment variables need to be read to construct it.

**Comment by amanda-tarafa** [comment]
@kurtisvg I'm sorry, but it really does not work how you are describing. Attached you can find an app that demonstrates how scoping per request works in the context of ASP.NET Core dependency injection. The app defines a `DummyService` that only counts the instances of it that are created. The type `DummyService` is registered as scoped for dependency injection. There's one controller with two actions `WithService` that acquires a service via DI and `WithoutService` that does not acquire a service. Both actions increment the amount of requests the app has received and return a text with info on the amount of requests and the amount of instances of `DummyService` that have been created. If you call `WithService` both request and instance counts increment by 1, as expected. If you call `WithoutService` only the request count increments. Which demonstrates what I've been trying to say:
- Scoped **does not mean** that each request will get a service (a connection in our case) wheter the request acquires it or not.
- Scoped means that **if and when a request acquires a service** for the first time (a connection in our case) and only then, a service instance will be created that will be shared for that whole request. The service, if disposable (as connections usually are) will be disposed of at the end of the request.

In the context of ASP.NET + ADO.NET, registering connections as scoped for DI is very much **not** an anti-pattern, and is widely used because of many advantages, including all advantages that come from DI.

So inmediately, your followwing concerns don't apply:

> 1. There an artificial limit on the number of requests that can be processed concurrently equal to the max side of the connection pool
> 2. Requests that don't use a database connection still consume a limited resource until a request is completed (which, as mentioned is maybe not a major barrier to this application - depending on when ADO.NET returns the inits/destroys the connection )

As for you concern:

> 3. Any time spent before or after the connection is blocking a resource that other requests are potentially blocked on (also mostly not applicable - but easily could be in a non-obvious way)

you can see on the docs that you yourself [linked](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling#pool-creation-and-assignment) that a pool is created or a connection is acquired from the pool when opening the connection, not when the connection is instantiated. So, we can even keep acquiring the connection at the beginning of the request and as long as we don't open it, we are not blocking anything.

Again, as I said earlier, I'm also fine with using `using` directly on the controller actions. I'm just trying to address your comments about the scoped connection not properly using the connection pool or even being an anti-pattern. Neither apply.

As for the DB initialization needing to be attempted just once at startup and not as part of connection acquisitions, I agree with you so much that I created this issue in the first place ;).

(I will change the issue title back to something that works better, given that connections are currently being properly shared between requests)

[TestingScoped.zip](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/files/5660455/TestingScoped.zip)

**Comment by kurtisvg** [comment]
@amanda-tarafa So I'll admit to discussing this conversation with one hand tied behind me back since I have an extremely limited experience with .NET. Please bear with me, as I want to make sure I full comprehend your side of the conversation here, because it doesn't seem to match with what I've seen in the docs and in other places. 

In the example you added, the service is specifically specified in the function signature:
```csharp
public string GetWithService([FromServices] DummyService service)
```
vs
```csharp
public string GetWithoutService()
```
However in our application, it looks like the [connection is bound to the entire Controller](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/cloud-sql/mysql/Controllers/HomeController.cs#L32-L35). Doesn't this mean that all endpoints inside that controller will scope a request, regardless if they are actually using it? 

Additionally, regarding my third concern:
> you can see on the docs that you yourself linked that a pool is created or a connection is acquired from the pool when opening the connection, not when the connection is instantiated. So, we can even keep acquiring the connection at the beginning of the request and as long as we don't open it, we are not blocking anything.

Here is the [portion of the ADO.NET documentation](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling) that makes me think that the connection object initialization blocks on having a connection ready:
> When a SqlConnection object is requested, it is obtained from the pool if a usable connection is available. To be usable, a connection must be unused, have a matching transaction context or be unassociated with any transaction context, and have a valid link to the server.
> 
> The connection pooler satisfies requests for connections by reallocating connections as they are released back into the pool. If the maximum pool size has been reached and no usable connection is available, the request is queued.

In our sample, our connection is neither opened or closed. So I guess I'm not really sure when it's opened if not at the start of the request, (maybe the command opens it on execution if it's not already opened?), but from both your statement above and the documentation it's defiantly not being closed until the end of request. We should be limiting the scope of the connection as tightly as possible to avoid blocking other requests, as [called out in the connection pooling docs](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling):

> We strongly recommend that you always close the connection when you are finished using it so that the connection will be returned to the pool.

From my understanding, this pattern is also [specifically out in the Dependency Injection](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#transient-limited-lifetime): 
> Scenario: The instance should be disposed before the scope ends.
> Solution:  Use the factory pattern to create an instance outside of the parent scope. In this situation, the app would generally have a Create method that calls the final type's constructor directly.

> In the context of ASP.NET + ADO.NET, registering connections as scoped for DI is very much not an anti-pattern, and is widely used because of many advantages, including all advantages that come from DI.

For the points I mentioned above, my stance is going to continue to be that this pattern is in fact an _anti_-pattern, since it encourages users to overscope their connection. I also want to clarify that I'm not suggesting we move to not using dependency injection, but that we change from injecting the DB URI instead of the connection itself. [This SO post here seems to more accurately capture the pattern I'm attempting to propose](https://stackoverflow.com/questions/14523166/is-there-a-simple-way-to-use-dependency-injection-on-my-connections).  Unless I'm missing something, I'm failing to see how using DI for the connection object over the URI would add any new benefits (but please continue to call me out if this is incorrect). 

Finally, one point which I think has been lost a bit higher up in the conversation is that these samples have a dual goals: The application itself _should_ show how to properly pass around a connection pool, but the snippet still needs to show the user how to open and close connections. [On the current page, we show the following](https://cloud.google.com/sql/docs/mysql/manage-connections#open-close-csharp):
```
insertTimestamp = DateTime.Now;
try
{
    using (var insertVoteCommand = _connection.CreateCommand())
    {
        insertVoteCommand.CommandText =
            @"INSERT INTO votes (candidate, time_cast) VALUES (@candidate, @time_cast)";
        // ... omitted
        await insertVoteCommand.ExecuteNonQueryAsync();
    }
    return Content($"Vote successfully cast for '{team}' at time {insertTimestamp}!");
}
catch (Exception ex)
{
   // ... omitted
}
```

In my opinion, this sample would be much more accurate if it show the using statement around the Connection, since currently the snippet isn't showing either the opening or the closing of the connection, which is not what the page describes. Would you agree, or am I missing something else?

**Comment by amanda-tarafa** [comment]
> Doesn't this mean that all endpoints inside that controller will scope a request, regardless if they are actually using it?

Yes, but that's why on the controller constructor you only inject services that are going to be used by all actions (as it's the case of these samples). And on each action you inject services that are going to be used by that action only (as is the case of my app). You can have all combinations. This is the standard way of using DI in ASP.NET.

> Here is the portion of the ADO.NET documentation that makes me think that the connection object initialization blocks on having a connection ready:
>
>> When a SqlConnection object is requested, it is obtained from the pool if a usable connection is available. ...

Requested here does not specifically refers to instantiation or opening, I agree this a poor wording though that might lead to confusion.
On those same docs, on the section [Pool Creation and Assigment](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling#pool-creation-and-assignment) you can specifically read that pools are created and connections are obtained from the pool on opening, not on instantiation:

> When a connection is first opened, a connection pool is created based on an exact matching algorithm that associates the pool with the connection string in the connection. Each connection pool is associated with a distinct connection string. When a new connection is opened, if the connection string is not an exact match to an existing pool, a new pool is created.

On the code example included in that section, you can also see how pool creation and connection pool obtention happens on opening:

```
using (SqlConnection connection = new SqlConnection(  
  "Integrated Security=SSPI;Initial Catalog=Northwind"))  
    {  
        connection.Open();
        // Pool A is created.  
    }  
  
using (SqlConnection connection = new SqlConnection(  
  "Integrated Security=SSPI;Initial Catalog=pubs"))  
    {  
        connection.Open();
        // Pool B is created because the connection strings differ.  
    }  
  
using (SqlConnection connection = new SqlConnection(  
  "Integrated Security=SSPI;Initial Catalog=Northwind"))  
    {  
        connection.Open();
        // The connection string matches pool A.  
    }
```
If you still have doubts, you can do a quick experiment. Write an app that uses a connection string with MaxPoolSize set to 10. Instantiate 100 connections and see if it blocks somewhere, open 11 and see what happens.

> In our sample, our connection is neither opened or closed.

It's opened [here](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/0218d48da2b99ef973a37a57a2aa649a2815554b/cloud-sql/sql-server/Startup.cs#L71) and will be closed at the end of the request once the original intent of this issue is adressed and the connection is registered as scoped instead of singleton, because it will be disposed of at the end of the request and disposing closes the connection. As I said earlier, the using block is just syntax sugar for making sure that `Dispose()` is always called but in this case that's not strictly necessary because DI takes care of that for us.
For applications whose actions only make DB operations as part of a bigger operation, it will make more sense to open and close the connection in the action. For applications whose operations are mostly DB operations (as these samples here, CRUD services and any other huge number of apps) it might be convenient to just acquire the connection opened and then having DI close it. (Yes, there are some ticks there in which the connection might be acquiered and iddle, I'd love to see benchamarks for a run-of-the-mill app where that's significant compared to the actual DB operations and the overall latency, an app depending so tightly on a few ticks, there's probably something else going on). Still, even if you were opening and closing the connection on the action itself, having the connection as scoped (which is what this all was about I think) won't ever hurt, it will actually help by making sure that even if you forgot a few `Close()` here and there, all connections will be actually closed and disposed of at the latest, at the end of the request.

>> We strongly recommend that you always close the connection when you are finished using it so that the connection will be returned to the pool. You can do this using either the Close or Dispose methods of the Connection object, or by opening all connections inside a using statement in C#, or a Using statement in Visual Basic. Connections that are not explicitly closed might not be added or returned to the pool.

(I've added the full quote to your partial one so there's more context.) And we would always do that with a scoped connection guaranteed by the DI mechanism. You yourself added "as tightly as possible", but see my comment before about ticks in an operation that performes DB operations. You can probably tweak my application and add a `Close` method to the `DummyService`. Call the `Close` method inside the action and store when it was called, store also when `Dispose` is called and see the differece.

>> Scenario: The instance should be disposed before the scope ends.

Definetely not the scenario if you call `Close()` in the action (which you definetely should do if you are doing heavy non DB operations after the DB operation), and benchmarking needed for "should be disposed before the scope ends" otherwise.

> I'm failing to see how using DI for the connection object over the URI would add any new benefits

It's harder to mock the connection if you want to do unit tests (which for the samples is totally fine by me, but not for someone wantint to base their application on the sample ;)). It's also harder to use the same connection at different points in your code and every part of your code would need to know whether the connection has been instantiated or not, etc (having all your code in the action is very particular of samples, but won't probably be the case for most normal apps). You would be passing all the work to the factory methods, when DI would do it for you if you register the connection factory directly.

As for the SO post, I'm not familiar with NInject so I wouldn't know the particulars. I would signal this bit though: 

> So I open and close the connection every single time that I need to perform a database operation.

Depending on how many single operations the app is doing, the connection pool could be stressed in a way that, even though you might end with more free connections at any given time, the pool is so busy acquiring and releasing connections that it takes longer for code to obtain a connection than if you just get one at the beginning of your operation and release it at the end.
As I said earlier, there's no one-size-fits-all, and developers really need to understand their requirements before blindly using what they see on any given sample.

> Finally, one point which I think has been lost a bit higher up in the conversation is that these samples have a dual goals:...

No, it didn't get lost, I already said: 

> The only thing that might tip me to swithching is that, in our docs, it's easier to show the snippet with the using, than to show the DI bits and the snippet using the connection separately.

And in any case, what I've been stressing all along: I'm not opposed to changing the sample, I'm not opposed to changing it to using `using` inside the action, or otherwise opening and closing the connection in the action. It's your call, and as long as is done in an idiomatica manner, I'll be fine with it, for these samples, both approaches work and I might very well agree with the `using` approach being simpler to understand.

What I'm pushing against is your blanket assertion that registering the connection for DI as scoped does not make proper use of connection pooling and thus doing so is an anti-pattern.

**Comment by kurtisvg** [comment]
> Requested here does not specifically refers to instantiation or opening, I agree this a poor wording though that might lead to confusion.
> ...
> f you still have doubts, you can do a quick experiment. Write an app that uses a connection string with MaxPoolSize set to 10. Instantiate 100 connections and see if it blocks somewhere, open 11 and see what happens.

I'll defer to your expertise here - that interpretation seems reasonable and makes sense to me. 

> Depending on how many single operations the app is doing, the connection pool could be stressed in a way that, even though you might end with more free connections at any given time, the pool is so busy acquiring and releasing connections that it takes longer for code to obtain a connection than if you just get one at the beginning of your operation and release it at the end.

I disagree that this is a realistic scenario - the number of checkouts/releases is generally the same, only with smaller scope (with the exception being if the original interpretation as checking-out/releasing a connection for multiple contiguous database operations, which I don't think was the intent of the original statement). Based on my experience, if your application spends a considerable amount of time waiting on connections, it's almost certainly because of a lack of connection availability and not locking stress on the pool itself.

> What I'm pushing against is your blanket assertion that registering the connection for DI as scoped does not make proper use of connection pooling and thus doing so is an anti-pattern.

I think we'll have to agree to disagree here then - IMO, this pattern clearly encourages users to over-scope the connection's lifespan. It makes it easy for a developer to accidentally check out/initialize them when they aren't used used, or for a user to forget to close them once it's done. While it _can_ be done properly, it requires extra effort to do correctly and can easily be missed. In my book, this makes it a classic example of an anti-pattern.

**Comment by amanda-tarafa** [comment]
> with the exception being if the original interpretation as checking-out/releasing a connection for multiple contiguous database operations, which I don't think was the intent of the original statement

This is what I was referring to actually, the person did say "every single time", but regardless of what they meant, it seems that we are in agreement here.

> this pattern clearly encourages users

My comment here is simple, there's no inevitability to using a pattern or anything else for that matter. You could say the developer chooses the pattern and not the other way around.

I've created a separete issue #1232 to track changing the samples to explicitly open and close the connection on the action methods. It's fine if these two issues are addressed on the same PR though.
