### ISSUE TITLE
Storage: HMAC key not inmediately available after creation?

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1367]
It seems that, even though the key has been successfully created, in some cases it is not inmediately available. @tritone is there a way to confirm this? Because if this is the case, we should add a sleep on samples, not just on tests, since this would be something that clients themselves will encounter.

**Comment by tritone** [comment]
@amanda-tarafa thanks for raising this issue.

We do note in the docs that users should wait [up to 3 min](https://cloud.google.com/storage/docs/authentication/managing-hmackeys) for changes to keys to propagate. Looks like this doc used to have a note that creation used to take up to 15s to go into effect as well (see internal cl/305900878), I'm not really sure why this was removed-- maybe we should ask for it to be reinstated.

In any case, I don't think it belongs in the body of the sample code since 1. it's something that's consistent across the API and 2. I don't think most users are hitting this endpoint super frequently via the library anyway given the low cap on number of keys.

I think we should add retries to the test for up to 15s after key creation (similar to [this](https://github.com/GoogleCloudPlatform/golang-samples/blob/77dddd2bf10d26891f37aa9215c660936d76e18a/storage/s3_sdk/s3_gcs_test.go#L49)) and put in a docs CL to reinstate that note -- how does that sound?

**Comment by amanda-tarafa** [comment]
OK, I'll add the retries when I have a chance and maybe you can try to have that piece of doc reinstated.
