### ISSUE TITLE
How should I check the authorization header in HTTP tasks?

### ISSUE THREAD

**Issue by atrauzzi** [GoogleCloudPlatform/dotnet-docs-samples#1645]
I feel like the C# example for cloud tasks is missing important details around how to check the authorization header.

Is there any chance of the example being expanded?

Can this be done without assuming that I'm on App Engine?  (I'm on Cloud Run)

**Comment by averikitsch** [comment]
Sorry for the slow reply. If you are targeting Cloud Run with a task then you should use an HTTP task with an OIDC service account. That service account should be given `run/invoker` permissions to invoke the Cloud Run services. This setup mean Cloud Run will automatically verify the authorization header instead of you implementing that yourself. [Click here to learn more](https://cloud.google.com/tasks/docs/creating-http-target-tasks#token). Please reopen if you have further questions

**Comment by averikitsch** [comment]
Right, you can deploy your Cloud Run service as private (`--no-allow-unauthenticated`).
