### ISSUE TITLE
The IOT tests are failing.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/dotnet-docs-samples#748]
I disabled them so that the nightly build succeeds.

Please submit a fix for the tests before making any other changes to the IOT code.

**Comment by munkhuushmgl** [comment]
I will fix it.

**Comment by munkhuushmgl** [comment]
IoT Core registries are limited 100 registries. It has reached 101 registries that was why it was failing.

**Comment by SurferJeffAtGoogle** [comment]
The tests are failing again:
![image](https://user-images.githubusercontent.com/11778530/54294686-e3ad1100-456e-11e9-9310-6a1ac7ae56c4.png)

**Comment by munkhuushmgl** [comment]
I have added limit checker method for reaching 100 registries.
I tested it, and it should not fail due to overloaded registries.

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/760

Best
Mike

**Comment by SurferJeffAtGoogle** [comment]
The last 8 test runs have failed:
![image](https://user-images.githubusercontent.com/11778530/54837876-ab02eb00-4c84-11e9-8e9e-daff73e86878.png)
![image](https://user-images.githubusercontent.com/11778530/54837948-cff75e00-4c84-11e9-8ddd-d01e69453c23.png)

**Comment by munkhuushmgl** [comment]
Hey Jefft,

I found the bug, and fixed it. Looks like there was an update on an error
message which I expected in Assert.Contains().
Since they changed the error message, it was not passing that specific test.

It tested it, and tests should be good now
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/769

Mike
