### ISSUE TITLE
Build error in Dialogflow V2 client.DetectIntent of session property 

### ISSUE THREAD

**Issue by amshekar** [GoogleCloudPlatform/dotnet-docs-samples#982]
Dear @SurferJeffAtGoogle 
under Google.Cloud.Dialogflow.V2 nuget package 
the associated SessionName method has three parameters `SessionName(string projectId, string locationId, string sessionId);` but in the following reference has only two parameters getting build error.
** what is the value that we supposed to pass for this locationId parameter**

Google.Cloud.Dialogflow.V2.SessionName class from  the component parts of pattern projects/{project}/locations/{location}/agent/sessions/{session}

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/2430da76c5daf8849328c6c01cf8c0c5de8b1c91/dialogflow/api/DialogflowSamples/DetectIntentTexts.cs#L56

Sample reference
.NetCore Console Application
Installed Google.Cloud.Dialogflow.V2 2.0.0 package from nuget 
gist reference [code snippet](https://gist.github.com/amshekar/6814b949822e616379a1b8adf47ce1a7)

**Comment by amanda-tarafa** [comment]
I will get back to you tomorrow morning GMT

**Comment by amanda-tarafa** [comment]
@amshekar 
You are using the latest version of our client library `Google.Cloud.Dialogflow.V2 2.0.0` (totally fine, keep doing that), while the samples are still using an older version (I will fix this later today), that's why you get the build error.

- Change the code to
`session: SessionName.FromProjectSession(projectId, sessionId),`
- I will update the sample project to use the latest client library today and will update the sample code with the above change.
- Longer explanation: A `SessionName` can be built in several different ways. [The `DetectIntent` operations requieres a `SessionName` built from a `projectId` and `sessionId`](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#detectintentrequest) so you should use the `SessionName.FromProjectSession` method to build it. You might need to use one of the other overloads in other places where the `SessionName` requieres a location for instance. You can read more about what each operation requires in the [Dialogflow client library documentation/reference](https://googleapis.dev/dotnet/Google.Cloud.Dialogflow.V2/2.0.0/index.html)  and also in the [Dialogflow RPV V2 API documentation](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2).

Let me know if there's something else I can do to help.
I will keep this issue opened until I've fixed the samples above.

**Comment by amshekar** [comment]
@amanda-tarafa  Thanks for your quick help.  It's worked like a charm

**Comment by amanda-tarafa** [comment]
Closing now since your particular Dialogflow issue has been addressed and fixing the sample itself if being tracked in #988 .
