### ISSUE TITLE
Training Phrase array ends up as a single text in dialogflow console

### ISSUE THREAD

**Issue by chuksgpfr** [GoogleCloudPlatform/dotnet-docs-samples#994]
The training phrase ends up as a single phrase after running my code.

this is my code 
           `string[] trainingPhrasesParts =
            {
                "Book a fligt",
                "check cheap flights"
            };

            var phraseParts = new List<Intent.Types.TrainingPhrase.Types.Part>();
            foreach (var part in trainingPhrasesParts)
            {
                phraseParts.Add(new Intent.Types.TrainingPhrase.Types.Part()
                {
                    Text = part
                });
            }

            var trainingPhrase = new Intent.Types.TrainingPhrase();
            trainingPhrase.Parts.AddRange(phraseParts);

            var intent = new Intent();
            intent.DisplayName = "test";
            //intent.Messages.Add(message);
            intent.TrainingPhrases.Add(trainingPhrase);`

This is how it shows in dialogflow 

> Book a fligtcheck cheap flights

@amanda-tarafa

**Comment by amanda-tarafa** [comment]
Please first note that the maintainers of this repo and of [googleapis/google-cloud-dotnet](https://github.com/googleapis/google-cloud-dotnet) are not experts on each individual API, just on the client libraries themselves.

That said, the result you are seing seems to be the expected result (see in the documentation for [TrainingPhrase](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#trainingphrase) the discription for `parts`). I believe that what you want to do is add **different** `TrainingPhrase`s and not a single `TrainingPhrase` with different `parts`.

I'll be closing this issue now since the problem you are experiencing doesn't seem to be related to the client library itself but is about API usage. If you still feel this is a problem with the client library please do leave another comment and I will reopen the issue if needed.

If you are having questions around how to use the Dialogflow API, you can go through the documentation [here](https://cloud.google.com/dialogflow/docs/reference/rpc) or take advantage of the support options available [here](https://cloud.google.com/dialogflow/docs/support/getting-support).

Please do create issues in [googleapis/google-cloud-dotnet](https://github.com/googleapis/google-cloud-dotnet) if you are experiencing problems with the client library or in this repo if the samples shown are failing or otherwise incorrect.
