### ISSUE TITLE
Dialogflow : ArgumentException: Wildcard resource ids must not contain / (Parameter 'value')

### ISSUE THREAD

**Issue by chuksgpfr** [GoogleCloudPlatform/dotnet-docs-samples#995]
I'm tryitn to create new entity with synonyms but im getting this error

> An unhandled exception occurred while processing the request.
ArgumentException: Wildcard resource ids must not contain / (Parameter 'value')

This is my code.

`

            EntityTypesClientBuilder builder = new EntityTypesClientBuilder
            {
                CredentialsPath = file
            };
            EntityTypesClient client = builder.Build();

            

            var entityType = new EntityType();
            entityType.DisplayName = "displayname";
            entityType.Kind = EntityType.Types.Kind.Map;

            var entityTypeId = client.CreateEntityType(new AgentName("chatbot-a90a9"), entityType);
            

            var entity = new EntityType.Types.Entity();
            entity.Synonyms.AddRange(synonyms);

            var operation = client.BatchCreateEntities(
                parent: new EntityTypeName("chatbot-a90a9", entityTypeId.Name),
                entities: new[] { entity }`

The error is on this line
`var operation = client.BatchCreateEntities(
                parent: new EntityTypeName("chatbot-a90a9", entityTypeId.Name),
                entities: new[] { entity }`

@amanda-tarafa

**Comment by jskeet** [comment]
Transferring this to google-cloud-dotnet as I don't believe this is a samples issue.

**Comment by amanda-tarafa** [comment]
You don't need to create a new EntityTypeName since you already have the one you need: 

```
var operation = client.BatchCreateEntities(
            parent: entityTypeId.Name,
            entities: new[] { entity },
            ...);
```
Also, maybe consider renaming the variable `entityTypeId` to `entityType` since the `CreateEntityType` method returns an `EntityType` instance and not just its ID.

[Here](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/dialogflow/api/DialogflowSamples) are some samples that will help you with basic Dialogflow operations.
